services:
  backend:
    container_name: hemuraback_dev
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dbs
    volumes:
      - /home/ninho/IdeaProjects/hemura:/app

networks:
    dbs:
        external: true